# YAML EXPLANATION FILE #

Name: Mr.kia
Languages: Python,Shell-script,Javascript,Php,Css,Powershell,Batch,C++,Java
Python-Version: Python 3 
Original Creator: Luca Garofalo (KIA)
Author: Luca Garofalo (KIA)
Copyright: (C) 2021-2023 KIA <lukege287@gmail.com>
Copyright-Years: 2021,2022,2023
Project-site: https://KIA.github.io/Mr.kia
Download: git clone https://github.com/KIA/Mr.kia
Platforms: Linux/MacOS/Termux/Windows
Version: T.G.D-1.0.4
License: GNU General Public License v3.0
